networks:
  traefik_default:
    external: true

services:
  server:
    cap_add:
      - NET_BIND_SERVICE
    cap_drop:
      - ALL
    image: git.zarantonello.dev/university/notes:v1.38.5@sha256:6b01da4dec38a56f46a965565fb0afc04f1906f5fab9b3781f3c385a23972adb
    labels:
      traefik.enable: true
      traefik.http.routers.university-notes.entrypoints: cloudflared
      traefik.http.routers.university-notes.rule: Host(`ice-notes.zarantonello.dev`)
      traefik.http.services.university-notes.loadbalancer.server.port: 80
    networks:
      - traefik_default
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 45383:45383
