networks:
  traefik_default:
    external: true

services:
  server:
    cap_add:
      - NET_BIND_SERVICE
    cap_drop:
      - ALL
    image: git.zarantonello.dev/university/notes:v1.38.4@sha256:707b76c36d4ed948fa58fb7a974035577490963b87b08ecb4d2bc33863ae81d2
    labels:
      traefik.enable: true
      traefik.http.routers.university-notes.entrypoints: cloudflared
      traefik.http.routers.university-notes.rule: Host(`ice-notes.zarantonello.dev`)
      traefik.http.services.university-notes.loadbalancer.server.port: 80
    networks:
      - traefik_default
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 45383:45383
