services:
  workspace:
    image: git.zarantonello.dev/infra/ci:v2.3.10@sha256:ef0ef90054d6fc1447f935fc5a8f8aedbbad0e3c34ed04727f058c8311b0c2d3
    ports:
      - 4321:4321
    volumes:
      - ..:/workspace:cached
