services:
  workspace:
    image: git.zarantonello.dev/infra/ci:v2.3.9@sha256:694151b154dc3e0e35b678b9c894703a91567d729e4085a0d733c0f066b529d5
    ports:
      - 4321:4321
    volumes:
      - ..:/workspace:cached
