services:
  workspace:
    image: git.zarantonello.dev/infra/ci:v2.3.22@sha256:a8093dfa3fde06d056300874eeb164f55f666978aa89c63ca8ed5654e2a37bdd
    ports:
      - 4321:4321
    volumes:
      - ..:/workspace:cached
