services:
  workspace:
    image: git.zarantonello.dev/infra/ci:v2.3.13@sha256:e048ec3b09ec34234087be9bc9ce66b4331aef82b98493f90316e15c2daaa6da
    ports:
      - 4321:4321
    volumes:
      - ..:/workspace:cached
