services:
  workspace:
    image: git.zarantonello.dev/infra/ci:v2.3.2@sha256:c063ef8c13e79da19caa49d1fb49da3e3f1d90acd19e2492ceddbca69d3a8309
    ports:
      - 4321:4321
    volumes:
      - ..:/workspace:cached
