services:
  workspace:
    image: git.zarantonello.dev/infra/ci:v2.3.1@sha256:1d781d38bd503df60d90910a062b580a3c457fd6d8b465f37887349c05419a28
    ports:
      - 4321:4321
    volumes:
      - ..:/workspace:cached
