services:
  workspace:
    image: git.zarantonello.dev/infra/ci:v2.2.5@sha256:76a732cc224ceca1c334515a1b10412fbe5ee53a3acd4d85d571f298620aee58
    ports:
      - 4321:4321
    volumes:
      - ..:/workspace:cached
