services:
  workspace:
    image: git.zarantonello.dev/infra/ci:v2.2.4@sha256:fa8f2a8c58c4780dd1e1848f1c33ef10f504fd89142786b952ba9ffe92dd8f00
    ports:
      - 4321:4321
    volumes:
      - ..:/workspace:cached
