services:
  workspace:
    image: git.zarantonello.dev/infra/ci:v2.2.8@sha256:dc5b80fcdf83ab30296d4ad2f051cb883c159af8bd881d986437e0c6e472a907
    ports:
      - 4321:4321
    volumes:
      - ..:/workspace:cached
