services:
  workspace:
    image: git.zarantonello.dev/infra/ci:v2.3.16@sha256:b4c91d2e15faf2e2d47d68b5577dd991167dd915b46fe6ffe1358dda7e74fe2f
    ports:
      - 4321:4321
    volumes:
      - ..:/workspace:cached
