services:
  workspace:
    image: git.zarantonello.dev/infra/ci:v2.3.23@sha256:9796473bded65fbf23fcc2f204366c4f5526fd366c61727b5d4685b20a963280
    ports:
      - 4321:4321
    volumes:
      - ..:/workspace:cached
