services:
  workspace:
    image: git.zarantonello.dev/infra/ci:v2.2.7@sha256:38f123c11ed0b69f904788fadd8324c92122a88fb347e54c568ab6f8e61c80d6
    ports:
      - 4321:4321
    volumes:
      - ..:/workspace:cached
