services:
  workspace:
    image: git.zarantonello.dev/infra/ci:v2.2.2@sha256:a3fe21ce07321802ac4e8e2ac25f68c8df09874f89a55b2e63ffb9519da737e4
    ports:
      - 4321:4321
    volumes:
      - ..:/workspace:cached
