services:
  workspace:
    image: git.zarantonello.dev/infra/ci:v2.3.14@sha256:7253ca97e8ad7c1c40f4830400952b8aee342592300515393c5fe2211e3ea780
    ports:
      - 4321:4321
    volumes:
      - ..:/workspace:cached
