services:
  workspace:
    image: git.zarantonello.dev/infra/ci:v2.3.8@sha256:3bb9a76d1cfd33f37dfc9ee89e3fe076e0b4f6a3fa41f05967f4ea47f528707b
    ports:
      - 4321:4321
    volumes:
      - ..:/workspace:cached
