services:
  workspace:
    image: git.zarantonello.dev/infra/ci:v2.3.5@sha256:7844ba8e37265d12533648b30a7582c0492cc48c5666b79feb131500bbf8649e
    ports:
      - 4321:4321
    volumes:
      - ..:/workspace:cached
