services:
  workspace:
    image: git.zarantonello.dev/infra/ci:v2.2.3@sha256:015a7cb8885d18943a72b67d11b6785f61d9f2eacc8927baf2cc4a653a8ca1b6
    ports:
      - 4321:4321
    volumes:
      - ..:/workspace:cached
