services:
  workspace:
    image: git.zarantonello.dev/infra/ci:v2.3.27@sha256:7c153472ecee9c9cb71dbfd440d488dee7b76a4aa04e8426ab930b01d5d05b29
    ports:
      - 4321:4321
    volumes:
      - ..:/workspace:cached
