services:
  workspace:
    image: git.zarantonello.dev/infra/ci:v2.3.4@sha256:cea8a53ec28792fa62c6802c3a627181ea95bbffba78248d5b3ab99c3b0462ca
    ports:
      - 4321:4321
    volumes:
      - ..:/workspace:cached
