services:
  workspace:
    image: git.zarantonello.dev/infra/ci:v2.3.6@sha256:3ed8788088e1f899f174d34c40099338ff2bdd43fc94374dcf818a0e74e341d0
    ports:
      - 4321:4321
    volumes:
      - ..:/workspace:cached
