services:
  workspace:
    image: git.zarantonello.dev/infra/ci:v2.3.7@sha256:ceb7771412a5ae7b3a992f087a6fcfce3f20d1583da7d5ba841307ce2334c94f
    ports:
      - 4321:4321
    volumes:
      - ..:/workspace:cached
