services:
  workspace:
    image: git.zarantonello.dev/infra/ci:v2.3.25@sha256:1e92ca12e445a6e0c098d8690e671b46645647a80a27d7f129ca35440c40add0
    ports:
      - 4321:4321
    volumes:
      - ..:/workspace:cached
