services:
  workspace:
    image: git.zarantonello.dev/infra/ci:v2.3.12@sha256:243783f21fa24487c6db0d94769f71a744d2de967683a41df26169ea1fd3a9f4
    ports:
      - 4321:4321
    volumes:
      - ..:/workspace:cached
