services:
  workspace:
    image: git.zarantonello.dev/infra/ci:v2.3.24@sha256:ded54f61957ab0a7ea98cc914e62cfd1f2669c8d4ed76da3ac44a59529d6b685
    ports:
      - 4321:4321
    volumes:
      - ..:/workspace:cached
