services:
  workspace:
    image: git.zarantonello.dev/infra/ci:v2.3.17@sha256:95c9217739ca18dd73bf0e424a859b7ba6e93090bf72ee6bda78f86f32a7a269
    ports:
      - 4321:4321
    volumes:
      - ..:/workspace:cached
