services:
  workspace:
    image: git.zarantonello.dev/infra/ci:v2.3.26@sha256:520a81b417306382b0ae94b86711cca7c064a571639baea3f33afd3326abdb34
    ports:
      - 4321:4321
    volumes:
      - ..:/workspace:cached
