apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: notes
spec:
  interval: 10m
  path: kubernetes
  prune: true
  sourceRef:
    kind: GitRepository
    name: notes
    namespace: university-notes
