apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes
spec:
  selector:
    matchLabels:
      apps.zarantonello.dev/name: notes
      apps.zarantonello.dev/namespace: university-notes
  template:
    metadata:
      labels:
        apps.zarantonello.dev/name: notes
        apps.zarantonello.dev/namespace: university-notes
    spec:
      containers:
        - image: git.zarantonello.dev/university/notes:v1.37.2@sha256:05c569b9592d6b22f8c21d615c64d4ae13161d2158c8a0a7fac4b26a2ebcb916
          imagePullPolicy: IfNotPresent
          name: notes
          ports:
            - containerPort: 80
              name: http
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
                - NET_BIND_SERVICE
              drop:
                - ALL
            readOnlyRootFilesystem: true
      enableServiceLinks: false
      nodeSelector:
        kubernetes.io/hostname: srv-0-nbg-hetz
      securityContext:
        fsGroup: 45383
        runAsGroup: 45383
        runAsNonRoot: true
        runAsUser: 45383
        seccompProfile:
          type: RuntimeDefault
